name: Laravel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
         host: ${{ secrets.SSH_HOST }}
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_PRIVATE_KEY }}
         port: ${{ secrets.SSH_PORT }}
         script: |
          cd /home/gold/public_html
          git stash
          git pull
          sudo update-alternatives --set php /usr/bin/php8.0
          composer update
          php artisan migrate
          sudo chmod 777 -R storage
          sudo chmod 777 -R bootstrap/cache
          php artisan optimize:clear
          php artisan cache:forget spatie.permission.cache


        #-----------------------------------------
        #php artisan optimize:clear
        #php artisan migrate:fresh --seed
        #sudo chmod 777 -R storage
        #sudo chmod 777 -R bootstrap/cache

        #-----------------------------------------
        #php artisan migrate
        #php artisan optimize:clear
