name: Laravel

on:
  push:
    branches: [ production ]
  pull_request:
    branches: [ production ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - name: Deploy to production
      uses: appleboy/ssh-action@master
      with:
         host: ${{ secrets.SSH_HOST_PROD }}
         username: ${{ secrets.SSH_USERNAME_PROD }}
         key: ${{ secrets.SSH_PRIVATE_KEY_PROD }}
         port: ${{ secrets.SSH_PORT_PROD }}
         script: |
          cd /home/pos/public_html
          git stash
          git pull
          sudo update-alternatives --set php /usr/bin/php8.0
          composer update
          php artisan migrate
          sudo chmod 777 -R storage
          sudo chmod 777 -R bootstrap/cache
          sudo composer clear-all

        #-----------------------------------------
        #php artisan schedule:run >> /dev/null 2>&1
        #-----------------------------------------
  
